name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.11.1'

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Parse sitemap
      run: |
        echo "https://open.shimo.im/sitemap.xml"
        # 解析Sitemap的代码，将得到的URL作为参数传递给后续步骤

    - name: Baidu API
      run: |
        echo "http://data.zz.baidu.com/urls?site=https://open.shimo.im&token=wX81OpgvaRbEysIT"
        # 调用百度接口的代码，使用解析出来的URL进行调用

